"""Static catalog data: vectors and GT programs."""

VECTORS = [
    {
        "serotype": "AAV1",
        "cargo_limit_bp": 4700,
        "tissue_tropism": ["muscle", "CNS"],
        "cns_tropic": 1,
        "retinal_tropic": 0,
        "hepatic_tropic": 0,
        "muscle_tropic": 1,
        "clinical_precedents": 8,
        "freely_available": 1,
    },
    {
        "serotype": "AAV2",
        "cargo_limit_bp": 4700,
        "tissue_tropism": ["retina", "liver", "CNS"],
        "cns_tropic": 1,
        "retinal_tropic": 1,
        "hepatic_tropic": 1,
        "muscle_tropic": 0,
        "clinical_precedents": 15,
        "freely_available": 1,
    },
    {
        "serotype": "AAV5",
        "cargo_limit_bp": 4700,
        "tissue_tropism": ["liver", "lung", "CNS"],
        "cns_tropic": 1,
        "retinal_tropic": 0,
        "hepatic_tropic": 1,
        "muscle_tropic": 0,
        "clinical_precedents": 12,
        "freely_available": 0,
    },
    {
        "serotype": "AAV8",
        "cargo_limit_bp": 4700,
        "tissue_tropism": ["liver", "muscle"],
        "cns_tropic": 0,
        "retinal_tropic": 0,
        "hepatic_tropic": 1,
        "muscle_tropic": 1,
        "clinical_precedents": 10,
        "freely_available": 0,
    },
    {
        "serotype": "AAV9",
        "cargo_limit_bp": 4700,
        "tissue_tropism": ["CNS", "muscle", "liver", "heart"],
        "cns_tropic": 1,
        "retinal_tropic": 0,
        "hepatic_tropic": 1,
        "muscle_tropic": 1,
        "clinical_precedents": 18,
        "freely_available": 1,
    },
    {
        "serotype": "AAVrh10",
        "cargo_limit_bp": 4700,
        "tissue_tropism": ["CNS", "liver"],
        "cns_tropic": 1,
        "retinal_tropic": 0,
        "hepatic_tropic": 1,
        "muscle_tropic": 0,
        "clinical_precedents": 5,
        "freely_available": 0,
    },
    {
        "serotype": "AAV2/6",
        "cargo_limit_bp": 4700,
        "tissue_tropism": ["liver", "muscle"],
        "cns_tropic": 0,
        "retinal_tropic": 0,
        "hepatic_tropic": 1,
        "muscle_tropic": 1,
        "clinical_precedents": 6,
        "freely_available": 0,
    },
    {
        "serotype": "LV",
        "cargo_limit_bp": 8000,
        "tissue_tropism": ["hematopoietic", "liver"],
        "cns_tropic": 0,
        "retinal_tropic": 0,
        "hepatic_tropic": 1,
        "muscle_tropic": 0,
        "clinical_precedents": 20,
        "freely_available": 1,
    },
]

GT_PROGRAMS = [
    {
        "name": "Zolgensma",
        "disease": "Spinal Muscular Atrophy",
        "gene_symbol": "SMN1",
        "vector": "AAV9",
        "tissue_target": "CNS/motor neuron",
        "cds_bp": 891,
        "approval_status": "approved",
        "approval_year": 2019,
        "mechanism": "gene_replacement",
        "protein_class": "intracellular",
        "inheritance": "AR",
        "pathway": "motor_neuron",
        "notes": None,
    },
    {
        "name": "Hemgenix",
        "disease": "Hemophilia B",
        "gene_symbol": "FIX",
        "vector": "AAV5",
        "tissue_target": "liver",
        "cds_bp": 1383,
        "approval_status": "approved",
        "approval_year": 2022,
        "mechanism": "gene_replacement",
        "protein_class": "secreted",
        "inheritance": "XL",
        "pathway": "coagulation",
        "notes": None,
    },
    {
        "name": "Roctavian",
        "disease": "Hemophilia A",
        "gene_symbol": "F8",
        "vector": "AAV5",
        "tissue_target": "liver",
        "cds_bp": 4374,
        "approval_status": "approved",
        "approval_year": 2023,
        "mechanism": "gene_replacement",
        "protein_class": "secreted",
        "inheritance": "XL",
        "pathway": "coagulation",
        "notes": None,
    },
    {
        "name": "Luxturna",
        "disease": "Leber congenital amaurosis type 2",
        "gene_symbol": "RPE65",
        "vector": "AAV2",
        "tissue_target": "retina/RPE",
        "cds_bp": 2646,
        "approval_status": "approved",
        "approval_year": 2017,
        "mechanism": "gene_replacement",
        "protein_class": "intracellular",
        "inheritance": "AR",
        "pathway": "retinal_visual_cycle",
        "notes": None,
    },
    {
        "name": "Glybera",
        "disease": "Lipoprotein lipase deficiency",
        "gene_symbol": "LPL",
        "vector": "AAV1",
        "tissue_target": "muscle",
        "cds_bp": 1527,
        "approval_status": "withdrawn",
        "approval_year": 2012,
        "mechanism": "gene_replacement",
        "protein_class": "secreted",
        "inheritance": "AR",
        "pathway": "lipid_metabolism",
        "notes": None,
    },
    {
        "name": "AT132",
        "disease": "X-linked myotubular myopathy",
        "gene_symbol": "MTM1",
        "vector": "AAV8",
        "tissue_target": "muscle",
        "cds_bp": 1878,
        "approval_status": "phase3",
        "approval_year": None,
        "mechanism": "gene_replacement",
        "protein_class": "intracellular",
        "inheritance": "XL",
        "pathway": "myopathy",
        "notes": None,
    },
    {
        "name": "SRP-9001",
        "disease": "Duchenne muscular dystrophy",
        "gene_symbol": "DMD_micro",
        "vector": "AAV9",
        "tissue_target": "muscle",
        "cds_bp": 3825,
        "approval_status": "approved",
        "approval_year": 2023,
        "mechanism": "gene_replacement",
        "protein_class": "membrane",
        "inheritance": "XL",
        "pathway": "myopathy",
        "notes": None,
    },
    {
        "name": "BMN 307",
        "disease": "Phenylketonuria",
        "gene_symbol": "PAH",
        "vector": "AAV5",
        "tissue_target": "liver",
        "cds_bp": 1353,
        "approval_status": "phase2",
        "approval_year": None,
        "mechanism": "gene_replacement",
        "protein_class": "intracellular",
        "inheritance": "AR",
        "pathway": "amino_acid_metabolism",
        "notes": None,
    },
    {
        "name": "GS010",
        "disease": "Leber hereditary optic neuropathy",
        "gene_symbol": "ND4",
        "vector": "AAV2",
        "tissue_target": "retina/RGC",
        "cds_bp": 1378,
        "approval_status": "approved",
        "approval_year": 2021,
        "mechanism": "gene_replacement",
        "protein_class": "intracellular",
        "inheritance": "mitochondrial",
        "pathway": "mitochondrial_complex",
        "notes": None,
    },
    {
        "name": "OAV101-IT",
        "disease": "Spinal Muscular Atrophy",
        "gene_symbol": "SMN1",
        "vector": "AAV9",
        "tissue_target": "CNS/spinal cord",
        "cds_bp": 891,
        "approval_status": "approved",
        "approval_year": 2020,
        "mechanism": "gene_replacement",
        "protein_class": "intracellular",
        "inheritance": "AR",
        "pathway": "motor_neuron",
        "notes": None,
    },
    {
        "name": "RGX-121",
        "disease": "Mucopolysaccharidosis type II",
        "gene_symbol": "IDS",
        "vector": "AAV9",
        "tissue_target": "CNS/liver",
        "cds_bp": 1659,
        "approval_status": "phase3",
        "approval_year": None,
        "mechanism": "gene_replacement",
        "protein_class": "secreted_lysosomal",
        "inheritance": "XL",
        "pathway": "lysosomal_storage",
        "notes": None,
    },
    {
        "name": "ABO-101",
        "disease": "Mucopolysaccharidosis type IIIB",
        "gene_symbol": "NAGLU",
        "vector": "AAV9",
        "tissue_target": "CNS",
        "cds_bp": 2238,
        "approval_status": "phase1/2",
        "approval_year": None,
        "mechanism": "gene_replacement",
        "protein_class": "secreted_lysosomal",
        "inheritance": "AR",
        "pathway": "lysosomal_storage",
        "notes": None,
    },
    {
        "name": "AVR-RD-01",
        "disease": "Fabry disease",
        "gene_symbol": "GLA",
        "vector": "LV",
        "tissue_target": "hematopoietic",
        "cds_bp": 1290,
        "approval_status": "phase1/2",
        "approval_year": None,
        "mechanism": "gene_replacement",
        "protein_class": "secreted_lysosomal",
        "inheritance": "XL",
        "pathway": "lysosomal_storage",
        "notes": None,
    },
    {
        "name": "ST-920",
        "disease": "Fabry disease",
        "gene_symbol": "GLA",
        "vector": "AAV2/6",
        "tissue_target": "liver",
        "cds_bp": 1290,
        "approval_status": "phase1/2",
        "approval_year": None,
        "mechanism": "gene_replacement",
        "protein_class": "secreted_lysosomal",
        "inheritance": "XL",
        "pathway": "lysosomal_storage",
        "notes": None,
    },
    {
        "name": "DTX301",
        "disease": "Ornithine transcarbamylase deficiency",
        "gene_symbol": "OTC",
        "vector": "AAV8",
        "tissue_target": "liver",
        "cds_bp": 1065,
        "approval_status": "phase2",
        "approval_year": None,
        "mechanism": "gene_replacement",
        "protein_class": "intracellular",
        "inheritance": "XL",
        "pathway": "urea_cycle",
        "notes": None,
    },
    {
        "name": "CPCB-RPE1",
        "disease": "Achromatopsia",
        "gene_symbol": "CNGB3",
        "vector": "AAV8",
        "tissue_target": "retina/photoreceptor",
        "cds_bp": 2499,
        "approval_status": "phase2/3",
        "approval_year": None,
        "mechanism": "gene_replacement",
        "protein_class": "membrane",
        "inheritance": "AR",
        "pathway": "retinal_phototransduction",
        "notes": None,
    },
    {
        "name": "SPK-8011",
        "disease": "Hemophilia A",
        "gene_symbol": "F8",
        "vector": "AAVrh10",
        "tissue_target": "liver",
        "cds_bp": 4374,
        "approval_status": "phase3",
        "approval_year": None,
        "mechanism": "gene_replacement",
        "protein_class": "secreted",
        "inheritance": "XL",
        "pathway": "coagulation",
        "notes": None,
    },
    {
        "name": "DTX201",
        "disease": "Hemophilia A",
        "gene_symbol": "F8",
        "vector": "AAV8",
        "tissue_target": "liver",
        "cds_bp": 4374,
        "approval_status": "phase2",
        "approval_year": None,
        "mechanism": "gene_replacement",
        "protein_class": "secreted",
        "inheritance": "XL",
        "pathway": "coagulation",
        "notes": None,
    },
]
